name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to a registry'
inputs:
  registry:
    description: 'Docker registry'
    required: true
  image_name:
    description: 'Docker image name'
    required: true
  docker_context:
    description: 'Docker context'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  publish:
    description: 'Publish the image'
    required: false
    default: "false"
runs:
  using: 'composite'
  steps:
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: 
          type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.docker_context }}
        push: ${{ inputs.publish == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # - name: Generate artifact attestation
    #   uses: actions/attest-build-provenance@v2
    #   with:
    #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
    #     subject-digest: ${{ steps.push.outputs.digest }}
    #     push-to-registry: ${{ inputs.publish == 'true' }}